version: "3.7"

services:
  app:
    build: .
    environment:
      TEST: "asd"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npx nodemon -L index.js
